// <auto-generated />
using System;
using BackendRestAPI.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendRestAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendRestAPI.Domain.Models.Assignment", b =>
                {
                    b.Property<int>("AssignmentPk")
                        .HasColumnType("integer")
                        .HasColumnName("assignment_pk");

                    b.Property<int>("AssignmentType")
                        .HasColumnType("integer")
                        .HasColumnName("assignment_type");

                    b.Property<DateOnly>("CreationDate")
                        .HasColumnType("date")
                        .HasColumnName("creation_date");

                    b.Property<int>("ReachablePoints")
                        .HasColumnType("integer")
                        .HasColumnName("reachable_points");

                    b.Property<int?>("SubjectFk")
                        .HasColumnType("integer")
                        .HasColumnName("subject_fk");

                    b.HasKey("AssignmentPk")
                        .HasName("assignment_pk");

                    b.HasIndex("SubjectFk");

                    b.ToTable("assignment", (string)null);
                });

            modelBuilder.Entity("BackendRestAPI.Domain.Models.Class", b =>
                {
                    b.Property<int>("PkClass")
                        .HasColumnType("integer")
                        .HasColumnName("pk_class");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("PkClass")
                        .HasName("class_pk");

                    b.ToTable("class", (string)null);
                });

            modelBuilder.Entity("BackendRestAPI.Domain.Models.Subject", b =>
                {
                    b.Property<int>("PkSubject")
                        .HasColumnType("integer")
                        .HasColumnName("pk_subject");

                    b.Property<int>("ClassFk")
                        .HasColumnType("integer")
                        .HasColumnName("class_fk");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("PkSubject")
                        .HasName("subject_pk");

                    b.HasIndex("ClassFk");

                    b.ToTable("subject", (string)null);
                });

            modelBuilder.Entity("BackendRestAPI.Domain.Models.Teacher", b =>
                {
                    b.Property<int>("PkTeacher")
                        .HasColumnType("integer")
                        .HasColumnName("pk_teacher");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstTitle")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("first_title");

                    b.Property<string>("LastTitle")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("last_title");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.HasKey("PkTeacher")
                        .HasName("teacher_pk");

                    b.ToTable("teachers", (string)null);
                });

            modelBuilder.Entity("BackendRestAPI.Models.ClassTeacher", b =>
                {
                    b.Property<int>("ClassTeacherPk")
                        .HasColumnType("integer")
                        .HasColumnName("class_teacher_pk");

                    b.Property<int?>("ClassFk")
                        .HasColumnType("integer")
                        .HasColumnName("class_fk");

                    b.Property<int?>("TeacherFk")
                        .HasColumnType("integer")
                        .HasColumnName("teacher_fk");

                    b.HasKey("ClassTeacherPk")
                        .HasName("class_teacher_pk");

                    b.HasIndex("ClassFk");

                    b.HasIndex("TeacherFk");

                    b.ToTable("class_teacher", (string)null);
                });

            modelBuilder.Entity("BackendRestAPI.Models.Student", b =>
                {
                    b.Property<int>("PkStudent")
                        .HasColumnType("integer")
                        .HasColumnName("pk_student");

                    b.Property<int?>("FkClass")
                        .HasColumnType("integer")
                        .HasColumnName("fk_class");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("PkStudent")
                        .HasName("student_pk");

                    b.HasIndex("FkClass");

                    b.ToTable("student", (string)null);
                });

            modelBuilder.Entity("BackendRestAPI.Models.StudentAssignment", b =>
                {
                    b.Property<int>("StudentAssignmentPk")
                        .HasColumnType("integer")
                        .HasColumnName("student_assignment_pk");

                    b.Property<int?>("AssignmentFk")
                        .HasColumnType("integer")
                        .HasColumnName("assignment_fk");

                    b.Property<int?>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<int?>("StudentFk")
                        .HasColumnType("integer")
                        .HasColumnName("student_fk");

                    b.HasKey("StudentAssignmentPk")
                        .HasName("student_assignment_pk");

                    b.HasIndex("AssignmentFk");

                    b.HasIndex("StudentFk");

                    b.ToTable("student_assignment", (string)null);
                });

            modelBuilder.Entity("BackendRestAPI.Domain.Models.Assignment", b =>
                {
                    b.HasOne("BackendRestAPI.Domain.Models.Subject", "SubjectFkNavigation")
                        .WithMany("Assignments")
                        .HasForeignKey("SubjectFk")
                        .HasConstraintName("subject_fk");

                    b.Navigation("SubjectFkNavigation");
                });

            modelBuilder.Entity("BackendRestAPI.Domain.Models.Subject", b =>
                {
                    b.HasOne("BackendRestAPI.Domain.Models.Class", "ClassFkNavigation")
                        .WithMany("Subjects")
                        .HasForeignKey("ClassFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("class_fk");

                    b.Navigation("ClassFkNavigation");
                });

            modelBuilder.Entity("BackendRestAPI.Models.ClassTeacher", b =>
                {
                    b.HasOne("BackendRestAPI.Domain.Models.Class", "ClassFkNavigation")
                        .WithMany("ClassTeachers")
                        .HasForeignKey("ClassFk")
                        .HasConstraintName("class_fk");

                    b.HasOne("BackendRestAPI.Domain.Models.Teacher", "TeacherFkNavigation")
                        .WithMany("ClassTeachers")
                        .HasForeignKey("TeacherFk")
                        .HasConstraintName("teacher_fk");

                    b.Navigation("ClassFkNavigation");

                    b.Navigation("TeacherFkNavigation");
                });

            modelBuilder.Entity("BackendRestAPI.Models.Student", b =>
                {
                    b.HasOne("BackendRestAPI.Domain.Models.Class", "FkClassNavigation")
                        .WithMany("Students")
                        .HasForeignKey("FkClass")
                        .HasConstraintName("class_fk");

                    b.Navigation("FkClassNavigation");
                });

            modelBuilder.Entity("BackendRestAPI.Models.StudentAssignment", b =>
                {
                    b.HasOne("BackendRestAPI.Domain.Models.Assignment", "AssignmentFkNavigation")
                        .WithMany("StudentAssignments")
                        .HasForeignKey("AssignmentFk")
                        .HasConstraintName("assignment_fk");

                    b.HasOne("BackendRestAPI.Models.Student", "StudentFkNavigation")
                        .WithMany("StudentAssignments")
                        .HasForeignKey("StudentFk")
                        .HasConstraintName("student_fk");

                    b.Navigation("AssignmentFkNavigation");

                    b.Navigation("StudentFkNavigation");
                });

            modelBuilder.Entity("BackendRestAPI.Domain.Models.Assignment", b =>
                {
                    b.Navigation("StudentAssignments");
                });

            modelBuilder.Entity("BackendRestAPI.Domain.Models.Class", b =>
                {
                    b.Navigation("ClassTeachers");

                    b.Navigation("Students");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("BackendRestAPI.Domain.Models.Subject", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("BackendRestAPI.Domain.Models.Teacher", b =>
                {
                    b.Navigation("ClassTeachers");
                });

            modelBuilder.Entity("BackendRestAPI.Models.Student", b =>
                {
                    b.Navigation("StudentAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
