name: ASP.NET Core CI

on:
  push:
    branches: [ main ]
    paths:
      - 'BackendRestAPI/BackendRestAPI/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'BackendRestAPI/BackendRestAPI/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' # Specify the .NET version

    - name: Change to Project Directory
      run: cd BackendRestAPI/BackendRestAPI

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    # Add additional steps for deployment or other jobs as needed




