name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore BackendRestAPI
    - name: Build
      run: dotnet build BackendRestAPI --no-restore
    - name: Test
      run: dotnet test BackendRestAPI --no-build --verbosity normal

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Publish
      run: |
        run: dotnet publish  -c Release --no-build




