# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy Angular App to Azure Web App

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x' # Specify your Node.js version

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: ./Frontend # F체gen Sie dies hinzu, um das Arbeitsverzeichnis zu 채ndern

      - name: Build Angular app
        run: npm run build -- --configuration production
        working-directory: ./Frontend # F체gen Sie dies hinzu, um das Arbeitsverzeichnis zu 채ndern

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C281A83DF87E4E43862395DD658A8D5A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F3029997253548D0BAB1A406F4A870C8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_272A0B8D1BED4F57BB2C01243BF75A0F }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'frontend'
          slot-name: 'Production'
          package: './dist/frontend'

