name: Get the latest version of the database

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up PostgreSQL client
        run: |
          sudo apt-get install postgresql-client

      - name: Drop and Recreate Schema
        run: |
           PGPASSWORD=${{ secrets.DB_PASSWORD }} psql -h dbnotenverwaltung.postgres.database.azure.com -U postgres -d postgres -c "DROP SCHEMA public CASCADE; CREATE SCHEMA public;"

      - name: Drop and Recreate Schema
        run: |
           PGPASSWORD=${{ secrets.DB_PASSWORD }} psql -h dbnotenverwaltung.postgres.database.azure.com -U postgres -d postgres -f ./backupDatabase/backup.sql
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

     


