name: Get the latest version of the database

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1


      - name: Pull the docker image
        run: docker pull schmidvinzent/dbnotenverwaltung:latest
        
      - name: Build the image new
        run: docker build -t schmidvinzent/dbnotenverwaltung:latest .

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login --username schmidvinzent --password-stdin
        
      - name: Tag the image with the new version
        run: docker tag schmidvinzent/dbnotenverwaltung:latest schmidvinzent/dbnotenverwaltung:latest

      - name: Run Docker Container
        run: docker run --name db -d schmidvinzent/dbnotenverwaltung:latest
  
      - name: Create SQL backup
        run: docker exec db pg_dump -U postgres postgres > ./backupDatabase/backup_$VERSION.sql
      
      - name: Push the image to Docker Hub
        run: docker push schmidvinzent/dbnotenverwaltung:latest

     


